# Generated by Django 2.0.7 on 2018-07-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(help_text='name of the board', max_length=20, unique=True),
        ),
    ]
