# Generated by Django 2.0.7 on 2018-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_auto_20180725_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
